import type { AwardDefinition, AwardType } from "./types";

// Rewards should be in increments of 50.
export const awardRedeemValues: Record<AwardType, number> = {
  first_trade: 50,
  profit_milestone_100: 50,
  profit_milestone_1000: 400,
  portfolio_value_1000: 300,
  portfolio_value_10000: 1500,
  diversified_portfolio: 100,
  top_trader: 1000,
  early_adopter: 200,
  comment_master: 50,
  social_butterfly: 50,
  welcome_bonus: 200,
  admin_ally: 150,
  friend_network_5: 100,
  friend_network_10: 200,
  friend_network_25: 500,
  buyback_starter: 100,
  buyback_broker: 300,
  stock_dilution_survivor: 75,
  early_bird_investor: 125,
};

export const awardDefinitions: Record<AwardType, AwardDefinition> = {
  welcome_bonus: {
    type: "welcome_bonus",
    name: "Welcome Bonus",
    description: "Claim your starter bonus",
    icon: "coins",
    rarity: "common",
    redeemableValue: awardRedeemValues.welcome_bonus,
  },
  first_trade: {
    type: "first_trade",
    name: "First Trade",
    description: "Made your first stock transaction",
    icon: "trending-up",
    rarity: "common",
    redeemableValue: awardRedeemValues.first_trade,
  },
  profit_milestone_100: {
    type: "profit_milestone_100",
    name: "Profit Seeker",
    description: "Earned $100 in total profits",
    icon: "trending-up",
    rarity: "common",
    redeemableValue: awardRedeemValues.profit_milestone_100,
  },
  profit_milestone_1000: {
    type: "profit_milestone_1000",
    name: "Wealth Builder",
    description: "Earned $1,000 in total profits",
    icon: "trophy",
    rarity: "rare",
    redeemableValue: awardRedeemValues.profit_milestone_1000,
  },
  portfolio_value_1000: {
    type: "portfolio_value_1000",
    name: "Portfolio Starter",
    description: "Built a portfolio worth $1,000",
    icon: "target",
    rarity: "common",
    redeemableValue: awardRedeemValues.portfolio_value_1000,
  },
  portfolio_value_10000: {
    type: "portfolio_value_10000",
    name: "Portfolio Master",
    description: "Built a portfolio worth $10,000",
    icon: "crown",
    rarity: "epic",
    redeemableValue: awardRedeemValues.portfolio_value_10000,
  },
  diversified_portfolio: {
    type: "diversified_portfolio",
    name: "Diversifier",
    description: "Own shares in 5 different stocks",
    icon: "users",
    rarity: "rare",
    redeemableValue: awardRedeemValues.diversified_portfolio,
  },
  top_trader: {
    type: "top_trader",
    name: "Top Trader",
    description: "Ranked #1 on the leaderboard",
    icon: "trophy",
    rarity: "legendary",
    redeemableValue: awardRedeemValues.top_trader,
  },
  early_adopter: {
    type: "early_adopter",
    name: "Early Adopter",
    description: "Joined during the beta period",
    icon: "star",
    rarity: "rare",
    redeemableValue: awardRedeemValues.early_adopter,
  },
  comment_master: {
    type: "comment_master",
    name: "Comment Master",
    description: "Posted 50 comments",
    icon: "message-square",
    rarity: "common",
    redeemableValue: awardRedeemValues.comment_master,
  },
  social_butterfly: {
    type: "social_butterfly",
    name: "Social Butterfly",
    description: "Started 10 conversations",
    icon: "users",
    rarity: "common",
    redeemableValue: awardRedeemValues.social_butterfly,
  },
  admin_ally: {
    type: "admin_ally",
    name: "Admin Ally",
    description: "Befriended an admin user",
    icon: "shield",
    rarity: "rare",
    redeemableValue: awardRedeemValues.admin_ally,
  },
  friend_network_5: {
    type: "friend_network_5",
    name: "Network Builder",
    description: "Built a network of 5 friends",
    icon: "users",
    rarity: "uncommon",
    redeemableValue: awardRedeemValues.friend_network_5,
  },
  friend_network_10: {
    type: "friend_network_10",
    name: "Influencer",
    description: "Built a network of 10 friends",
    icon: "crown",
    rarity: "rare",
    redeemableValue: awardRedeemValues.friend_network_10,
  },
  friend_network_25: {
    type: "friend_network_25",
    name: "Celebrity",
    description: "Built a network of 25 friends",
    icon: "star",
    rarity: "epic",
    redeemableValue: awardRedeemValues.friend_network_25,
  },
  buyback_starter: {
    type: "buyback_starter",
    name: "Buyback Starter",
    description: "Accepted your first buyback offer",
    icon: "arrow-up",
    rarity: "uncommon",
    redeemableValue: awardRedeemValues.buyback_starter,
  },
  buyback_broker: {
    type: "buyback_broker",
    name: "Buyback Broker",
    description: "Accepted 5 buyback offers",
    icon: "trending-up",
    rarity: "rare",
    redeemableValue: awardRedeemValues.buyback_broker,
  },
  stock_dilution_survivor: {
    type: "stock_dilution_survivor",
    name: "Dilution Survivor",
    description: "Own a stock that was diluted through share creation",
    icon: "alert-circle",
    rarity: "uncommon",
    redeemableValue: awardRedeemValues.stock_dilution_survivor,
  },
  early_bird_investor: {
    type: "early_bird_investor",
    name: "Early Bird Investor",
    description: "Bought shares in a stock within an hour of its release",
    icon: "zap",
    rarity: "rare",
    redeemableValue: awardRedeemValues.early_bird_investor,
  },
};
