import type { AwardDefinition, AwardType } from "./types";

// Rewards should be in increments of 50.
export const awardRedeemValues: Record<AwardType, number> = {
  first_trade: 50,
  profit_milestone_100: 50,
  profit_milestone_1000: 400,
  portfolio_value_1000: 300,
  portfolio_value_10000: 1500,
  diversified_portfolio: 100,
  top_trader: 1000,
  early_adopter: 200,
  comment_master: 50,
  social_butterfly: 50,
  welcome_bonus: 200,
};

export const awardDefinitions: Record<AwardType, AwardDefinition> = {
  welcome_bonus: {
    type: "welcome_bonus",
    name: "Welcome Bonus",
    description: "Claim your starter bonus",
    icon: "coins",
    rarity: "common",
    redeemableValue: awardRedeemValues.welcome_bonus,
  },
  first_trade: {
    type: "first_trade",
    name: "First Trade",
    description: "Made your first stock transaction",
    icon: "trending-up",
    rarity: "common",
    redeemableValue: awardRedeemValues.first_trade,
  },
  profit_milestone_100: {
    type: "profit_milestone_100",
    name: "Profit Seeker",
    description: "Earned $100 in total profits",
    icon: "trending-up",
    rarity: "common",
    redeemableValue: awardRedeemValues.profit_milestone_100,
  },
  profit_milestone_1000: {
    type: "profit_milestone_1000",
    name: "Wealth Builder",
    description: "Earned $1,000 in total profits",
    icon: "trophy",
    rarity: "rare",
    redeemableValue: awardRedeemValues.profit_milestone_1000,
  },
  portfolio_value_1000: {
    type: "portfolio_value_1000",
    name: "Portfolio Starter",
    description: "Built a portfolio worth $1,000",
    icon: "target",
    rarity: "common",
    redeemableValue: awardRedeemValues.portfolio_value_1000,
  },
  portfolio_value_10000: {
    type: "portfolio_value_10000",
    name: "Portfolio Master",
    description: "Built a portfolio worth $10,000",
    icon: "crown",
    rarity: "epic",
    redeemableValue: awardRedeemValues.portfolio_value_10000,
  },
  diversified_portfolio: {
    type: "diversified_portfolio",
    name: "Diversifier",
    description: "Own shares in 5 different stocks",
    icon: "users",
    rarity: "rare",
    redeemableValue: awardRedeemValues.diversified_portfolio,
  },
  top_trader: {
    type: "top_trader",
    name: "Top Trader",
    description: "Ranked #1 on the leaderboard",
    icon: "trophy",
    rarity: "legendary",
    redeemableValue: awardRedeemValues.top_trader,
  },
  early_adopter: {
    type: "early_adopter",
    name: "Early Adopter",
    description: "Joined during the beta period",
    icon: "star",
    rarity: "rare",
    redeemableValue: awardRedeemValues.early_adopter,
  },
  comment_master: {
    type: "comment_master",
    name: "Comment Master",
    description: "Posted 50 comments",
    icon: "message-square",
    rarity: "common",
    redeemableValue: awardRedeemValues.comment_master,
  },
  social_butterfly: {
    type: "social_butterfly",
    name: "Social Butterfly",
    description: "Started 10 conversations",
    icon: "users",
    rarity: "common",
    redeemableValue: awardRedeemValues.social_butterfly,
  },
};
